package amazon

// BusinessModels returns every Amazon model that must exist before Amazon
// features are usable.
func BusinessModels() []interface{} {
	return []interface{}{
		&FinanceFXRate{},
		&FinanceImportJob{},
		&AmazonAdsAccount{},
		&FinanceAdReportLine{},
		&FinanceCostBill{},
		&FinanceCostBillLine{},
		&FinanceCostPool{},
		&FinanceCostMovement{},
		&FinanceSettlementBatch{},
		&FinanceSettlementLine{},
		&FinanceEntry{},
		&FinanceOrderSnapshot{},
		&FinancePeriodSummary{},
		&FinanceReceivable{},
		&FinancePayable{},
		&FinancePaymentRecord{},
		&FinanceQuestion{},
		&FinanceQuestionType{},
		&FinanceRecalcJob{},
		&LogisticsUploadBatch{},
		&LogisticsChannelVersion{},
		&LogisticsRateRowVersion{},
		&ListingTemplate{},
		&ListingTemplateField{},
		&ListingFamily{},
		&ListingItem{},
		&ListingItemMarketplace{},
		&ListingItemLocale{},
		&ListingItemImage{},
		&ListingProfitProfile{},
		&CollectedProduct{},
		&CollectedProductImage{},
		&Collected1688Product{},
		&Collected1688ProductImage{},
		&Collect1688Task{},
		&Collect1688Binding{},
		&FulfillmentProfile{},
		&StoreAccount{},
		&ListingPublishJob{},
		&ListingPublishRecord{},
		&ListingSyncJob{},
		&ListingSyncRecord{},
		&Order{},
		&OrderItem{},
		&OrderAddress{},
		&OrderProcurementGroup{},
		&OrderProcurementGroupItem{},
		&OrderShipment{},
		&OrderSyncJob{},
		&SupportCase{},
		&SupportCaseMessage{},
		&SupportTemplate{},
		&SupportImportJob{},
		&ReturnServiceProvider{},
		&ReturnWarehouse{},
		&ReturnOrder{},
		&ReturnItem{},
		&ReturnDisposition{},
		&ReturnSyncJob{},
	}
}
